import type { GameConfig } from '../types'

export const idleCivilizationsConfig: GameConfig = {
  id: 'idle-civilizations',
  displayName: 'Idle Civilizations',
  tagline: 'Start with a spark. End among the stars.',
  subtitle: 'Build History. Earn Gold.',
  description: 'Idle Civilizations is the idle game for history lovers. Begin with nothing but a campfire in the Stone Age and build your civilization through 8 iconic eras — all the way to the Space Age.',
  appStoreId: '6760996636',
  appStoreUrl: 'https://apps.apple.com/app/id6760996636',
  status: 'live',
  accentColor: '#C8A84B',
  backgroundColor: '#0D0D0F',
  appIconAsset: 'AppIcon-1024',
  heroArtworkAsset: 'era_space_age',
  stats: {
    levelCount: 8,
    unitCount: 40,
    milestoneCount: 8,
    leaderCount: 5,
  },
  vocab: {
    levelPlural: 'Eras',
    unitPlural: 'Buildings',
    milestonePlural: 'Wonders',
    characterPlural: 'Leaders',
    prestigeVerb: 'Found New Empire',
    premiumPassName: 'Civ Pass',
  },
  eras: [
    { id: 'stone_age', displayName: 'Stone Age', order: 1, artworkAsset: 'era_stone_age', primaryColor: '#8B7355', secondaryColor: '#6B5A3E', flavorText: 'A campfire, a dream, and absolutely zero plumbing.' },
    { id: 'bronze_age', displayName: 'Bronze Age', order: 2, artworkAsset: 'era_bronze_age', primaryColor: '#B8860B', secondaryColor: '#8B6914', flavorText: 'Finally, tools. And weapons. Mostly weapons.' },
    { id: 'ancient_empires', displayName: 'Ancient Empires', order: 3, artworkAsset: 'era_ancient_empires', primaryColor: '#C4A24D', secondaryColor: '#9C7D35', flavorText: 'Pyramids, pharaohs, and surprisingly good math.' },
    { id: 'classical_world', displayName: 'Classical World', order: 4, artworkAsset: 'era_classical_world', primaryColor: '#A0836D', secondaryColor: '#7D6354', flavorText: "Rome wasn't built in a day. Yours might be." },
    { id: 'medieval_era', displayName: 'Medieval Era', order: 5, artworkAsset: 'era_medieval_era', primaryColor: '#4A6741', secondaryColor: '#364E30', flavorText: 'Castles, cathedrals, and questionable hygiene standards.' },
    { id: 'renaissance', displayName: 'Renaissance', order: 6, artworkAsset: 'era_renaissance', primaryColor: '#7B5E8A', secondaryColor: '#5E4469', flavorText: 'Art, science, and da Vinci doing literally everything.' },
    { id: 'industrial_revolution', displayName: 'Industrial Revolution', order: 7, artworkAsset: 'era_industrial_revolution', primaryColor: '#5A6E7A', secondaryColor: '#3D4F58', flavorText: 'Smoke, steam, and the invention of the 80-hour work week.' },
    { id: 'space_age', displayName: 'Space Age', order: 8, artworkAsset: 'era_space_age', primaryColor: '#2E3A8C', secondaryColor: '#1A2466', flavorText: 'From campfire to lunar base. Not bad for a few clicks.' },
  ],
  wonders: [
    { id: 'lascaux_cave', displayName: 'Lascaux Cave', artworkAsset: 'ms_lascaux_cave', era: 'Stone Age', bonus: '+50% Tribal Production' },
    { id: 'stonehenge', displayName: 'Stonehenge', artworkAsset: 'ms_stonehenge', era: 'Bronze Age', bonus: '+100% Bronze Income' },
    { id: 'great_library', displayName: 'Great Library', artworkAsset: 'ms_great_library', era: 'Ancient Empires', bonus: '+75% Culture Production' },
    { id: 'parthenon', displayName: 'Parthenon', artworkAsset: 'ms_parthenon', era: 'Classical World', bonus: '+100% Faith & Gold' },
    { id: 'notre_dame', displayName: 'Notre-Dame', artworkAsset: 'ms_notre_dame', era: 'Medieval Era', bonus: '+150% Cathedral Output' },
    { id: 'sistine_chapel', displayName: 'Sistine Chapel', artworkAsset: 'ms_sistine_chapel', era: 'Renaissance', bonus: '+200% Science Generation' },
    { id: 'crystal_palace', displayName: 'Crystal Palace', artworkAsset: 'ms_crystal_palace', era: 'Industrial Revolution', bonus: '+250% Factory Output' },
    { id: 'international_space_station', displayName: 'Space Station', artworkAsset: 'ms_international_space_station', era: 'Space Age', bonus: '×2 Global Gold (Permanent)' },
  ],
  leaders: [
    { id: 'og_the_elder', displayName: 'Og the Elder', era: 'Stone Age', portraitAsset: 'char_og_the_elder', keyBonus: 'Campfire ×1.10' },
    { id: 'hammurabi', displayName: 'Hammurabi', era: 'Bronze Age', portraitAsset: 'char_hammurabi', keyBonus: 'Marketplace ×1.20' },
    { id: 'julius_caesar', displayName: 'Julius Caesar', era: 'Classical World', portraitAsset: 'char_julius_caesar', keyBonus: 'Roman Legions ×1.25' },
    { id: 'da_vinci', displayName: 'Leonardo da Vinci', era: 'Renaissance', portraitAsset: 'char_da_vinci', keyBonus: 'Workshop ×1.30' },
    { id: 'nikola_tesla', displayName: 'Nikola Tesla', era: 'Industrial Revolution', portraitAsset: 'char_nikola_tesla', keyBonus: 'Power Station ×1.25' },
  ],
  buildingShowcase: [
    { id: 'campfire', displayName: 'Campfire', iconAsset: 'unit_campfire', era: 'Stone Age' },
    { id: 'tribal_elder', displayName: 'Tribal Elder', iconAsset: 'unit_tribal_elder', era: 'Stone Age' },
    { id: 'mine', displayName: 'Mine', iconAsset: 'unit_mine', era: 'Bronze Age' },
    { id: 'marketplace', displayName: 'Marketplace', iconAsset: 'unit_marketplace', era: 'Bronze Age' },
    { id: 'great_pyramid', displayName: 'Great Pyramid', iconAsset: 'unit_great_pyramid', era: 'Ancient Empires' },
    { id: 'colosseum', displayName: 'Colosseum', iconAsset: 'unit_colosseum', era: 'Classical World' },
    { id: 'roman_legions', displayName: 'Roman Legions', iconAsset: 'unit_roman_legions', era: 'Classical World' },
    { id: 'castle', displayName: 'Castle', iconAsset: 'unit_castle', era: 'Medieval Era' },
    { id: 'cathedral', displayName: 'Cathedral', iconAsset: 'unit_cathedral', era: 'Medieval Era' },
    { id: 'printing_press', displayName: 'Printing Press', iconAsset: 'unit_printing_press', era: 'Renaissance' },
    { id: 'da_vinci_workshop', displayName: "Da Vinci's Workshop", iconAsset: 'unit_da_vinci_workshop', era: 'Renaissance' },
    { id: 'factory', displayName: 'Factory', iconAsset: 'unit_factory', era: 'Industrial Revolution' },
    { id: 'power_station', displayName: 'Power Station', iconAsset: 'unit_power_station', era: 'Industrial Revolution' },
    { id: 'computer_lab', displayName: 'Computer Lab', iconAsset: 'unit_computer_lab', era: 'Space Age' },
    { id: 'space_rocket', displayName: 'Space Rocket', iconAsset: 'unit_space_rocket', era: 'Space Age' },
    { id: 'lunar_base', displayName: 'Lunar Base', iconAsset: 'unit_lunar_base', era: 'Space Age' },
  ],
  features: [
    { icon: 'Moon', title: 'Works Completely Offline', description: 'Your empire never stops growing. Earn income while you sleep, commute, or conquer.' },
    { icon: 'Zap', title: 'No Energy System', description: 'Play as much as you want, whenever you want. No timers, no paywalls on playtime.' },
    { icon: 'Crown', title: '5 Legendary Leaders', description: 'Unlock Hammurabi, Julius Caesar, da Vinci, Tesla, and more. Each transforms your economy.' },
    { icon: 'Trophy', title: '8 World Wonders', description: 'Build Stonehenge, the Great Library, Notre-Dame, and the International Space Station.' },
    { icon: 'RotateCcw', title: 'Prestige & Legacy Tokens', description: 'Found a New Empire to earn permanent multipliers. Every reset makes you stronger.' },
    { icon: 'Globe', title: 'Weekly Competitions', description: 'Compete in Olympic Games and seasonal exhibitions against players worldwide.' },
  ],
  supportEmail: 'vmihai12@icloud.com',
  privacyPolicyLastUpdated: '2026-03-23',
  supportFAQ: [
    {
      question: 'My offline income seems low. Is that normal?',
      answer: 'Offline income is calculated at a reduced rate compared to active play. Make sure you have managers hired for all your buildings — buildings without managers do not produce while offline.',
    },
    {
      question: 'I lost my progress after reinstalling. How do I restore it?',
      answer: "Your progress is saved to iCloud automatically. Sign into the same Apple ID on your new device and launch the game — your save should restore within a few seconds. If it doesn't appear, check that iCloud Drive is enabled in Settings > [Your Name] > iCloud.",
    },
    {
      question: 'How does the Civ Pass subscription work?',
      answer: "The Civ Pass is an optional monthly subscription that grants bonus coins, a permanent gold multiplier, and exclusive cosmetic perks. It auto-renews monthly. You can cancel at any time from your iPhone's Subscriptions settings.",
    },
    {
      question: 'Are ads required to progress?',
      answer: 'No. Rewarded ads are completely optional and never forced. You can play through all 8 eras without ever watching an ad.',
    },
    {
      question: 'What happens when I prestige (Found New Empire)?',
      answer: 'Prestiging resets your buildings and gold back to the beginning, but you earn Legacy Tokens — permanent multipliers that stack across every future run.',
    },
    {
      question: 'I have a bug or a suggestion. How do I contact you?',
      answer: 'Email us at vmihai12@icloud.com — we read every message and usually respond within 1 business day.',
    },
  ],
}
