import type { GameConfig } from '../types'

export const idleRestaurantEmpireConfig: GameConfig = {
  id: 'idle-restaurant-empire',
  displayName: 'Idle Restaurant Empire',
  tagline: 'From food truck to Michelin star.',
  subtitle: 'Cook. Serve. Conquer.',
  description: 'Build your culinary empire from a humble food truck to a global restaurant dynasty.',
  appStoreId: '',
  appStoreUrl: '',
  status: 'coming-soon',
  accentColor: '#E85D3A',
  backgroundColor: '#0F0A08',
  appIconAsset: 'AppIcon-1024',
  heroArtworkAsset: 'cuisine_hero',
  stats: { levelCount: 8, unitCount: 40, milestoneCount: 8, leaderCount: 5 },
  vocab: {
    levelPlural: 'Cuisine Eras',
    unitPlural: 'Dishes',
    milestonePlural: 'Michelin Stars',
    characterPlural: 'Head Chefs',
    prestigeVerb: 'New Cuisine Unlocked',
    premiumPassName: "Chef's Table",
  },
  eras: [],
  wonders: [],
  leaders: [],
  buildingShowcase: [],
  features: [
    { icon: 'ChefHat', title: 'From Truck to Empire', description: 'Progress through 8 cuisine eras from Street Food to Molecular Gastronomy.' },
    { icon: 'Star', title: 'Michelin Stars', description: 'Earn prestigious stars as you master each cuisine era.' },
    { icon: 'Moon', title: 'Works Offline', description: 'Your kitchen never sleeps — earn income 24/7.' },
    { icon: 'Zap', title: 'No Energy System', description: 'Cook as much as you want, whenever you want.' },
    { icon: 'Trophy', title: '5 Legendary Chefs', description: 'Unlock famous chefs who transform your kitchen output.' },
    { icon: 'Globe', title: 'Weekly Cook-offs', description: 'Compete against players worldwide in timed cooking competitions.' },
  ],
  supportEmail: 'vmihai12@icloud.com',
  privacyPolicyLastUpdated: '2026-03-23',
  termsLastUpdated: '2026-03-30',
  supportFAQ: [],
}
